name: flutter_news_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #* UI
  cupertino_icons: ^1.0.2
  fancy_shimmer_image: ^2.0.2
  card_swiper: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.3
  shimmer: ^2.0.0
  webview_flutter: ^4.2.0

  #*REST API
  http: ^0.13.5

  #* Management
  intl: ^0.18.1
  provider: ^6.0.5

  #* Social
  share_plus: ^4.5.3
  url_launcher: ^6.1.10

#* Build
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  rename: ^2.1.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_kabar.png"
  min_sdk_android: 21

  #*Splash Screen
flutter_native_splash:
  android: true
  ios: true
  color: "FFFFFF"
  image: assets/images/splash_img.png

flutter:
  uses-material-design: true

  #*Asset
  assets:
    - assets/icons/
    - assets/images/
